# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    body_converter:
        enabled: true
    format_listener:
        enabled: true
        rules:
        - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ 'json' ] }
        - { path: ^/, stop: true }
    exception:
        enabled: true
        codes:
            App\Exception\PersistenceLayerException: HTTP_SERVICE_UNAVAILABLE
            App\Exception\ValidationException: HTTP_BAD_REQUEST
            App\Exception\BulkValidationException: HTTP_BAD_REQUEST
            Symfony\Component\HttpKernel\Exception\NotFoundHttpException: HTTP_NOT_FOUND
            Exception: HTTP_INTERNAL_SERVER_ERROR
        messages:
            App\Exception\PersistenceLayerException: false
            App\Exception\ValidationException: false
            App\Exception\BulkValidationException: false
            Symfony\Component\HttpKernel\Exception\NotFoundHttpException: false
            Exception: false
