# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    body_converter:
        enabled: true
    format_listener:
        enabled: true
        rules:
        - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ 'json' ] }
    exception:
        enabled: true
        codes:
            App\Exception\PersistenceLayerException: HTTP_SERVICE_UNAVAILABLE
            Exception: HTTP_INTERNAL_SERVER_ERROR
        messages:
            App\Exception\PersistenceLayerException: false
            Exception: false
