nelmio_api_doc:
    models: { use_jms: false }
    routes:
        path_patterns:
            - ^/api/[^doc]
    documentation:
        info:
            title: Phash Server API
            description: These are the Endpoints for the phash Server
            version: '0.1'
        securityDefinitions:
            api_key:
                type: apiKey
                description: Your Auth Token
                name:  Authorization
                in: header
        security:
            - api_key: []