App\Dto\MonitoringData:
    properties:
        path:
            - \App\Validator\Constraints\IsBranch: ~
            - \App\Validator\Constraints\IsLeaf: ~
        tileExpansionGrowthExpression:
            - Regex:
                pattern: '/[\+\*]\s*\d+/'
                message: Growth expression {{ value }} is invalid
